### ISSUE TITLE
The option `--hide-prelude` expects an argument.

### ISSUE THREAD

**Issue by cbh34680** [well-typed/visualize-cbn#24]
I tried Stepping through as follows:

```
ubuntu@vm1:~/visualize-cbn$ ~/.local/bin/visualize-cbn -i examples/fac.hs --show-trace --hide-prelude
The option --hide-prelude expects an argument.

Usage: visualize-cbn -i INPUT-FILE [--show-trace] [--gc] [--selector-thunk-opt]
                     [--inline-heap] [--collapse-beta] [--max-num-steps N]
                     [--hide-prelude STEP] [--hide-term ARG] [--hide-gc]
                     [--hide-selector-thunk-opt] [--hide-inlining]
                     [--javascript JS-FILE] [--javascript-function JS-NAME]
                     [--graph GRAPH-FILE] [--heap-graph PATH/FILES-PREFIX]
                     [--disable-ansi]
```

`--hide-prelude STEP`

What should I specify for STEP?

**Comment by edsko** [comment]
I see that the README suggests you always pass this flag, that's a documentation bug: that's not necessary, you can just omit it. If you want to use it, it's the number of a step in the reduction, and then the prelude will be hidden for all steps beyond that point. (The goal here is to reduce clutter by not showing the prelude all the time, but still be able to see it at the beginning, so that you know what the prelude _is_).

**Comment by cbh34680** [comment]
` it's the number of a step in the reduction`

I could understand that

```
ubuntu@vm1:~/visualize-cbn$ ~/.local/bin/visualize-cbn -i examples/fac.hs --show-trace --hide-prelude 0
```

When I run it like above, it shows as written in README.

Thank you for your answer.

**Comment by edsko** [comment]
Glad it helped :) I've fixed the README.
